### ISSUE TITLE
Add single error exploration

### ISSUE THREAD

**Issue by martinagvilas** [pandanistas/docstring_notebooks#5]
We need to add the possibility to explore in detail one of the errors in the file. The error to be explored should be an input from the user.

**Comment by galuhsahid** [comment]
Hi Martina! If you're not already working on this, I can help with this. However can you elaborate what "explore in detail" means? Just trying to get an idea of what kind of details should be surfaced to the users. Thanks!

**Comment by martinagvilas** [comment]
Hi @galuhsahid! I was referring to the part of the notebook were we say: 

> Select an error from the following dropdown menu to see a complete description and example of it, and the number of that type of errors in pandas:

That part is not finished yet. I think the idea was that if I select, say, error 'E03' from the dropdown menu, a full description of that type of error is printed, along with an example of how would that look (I think we have all this in the wiki so we could simply transfer that information).

But apart from that, we could also add an interactive widget at the very last part of the notebook where a specific error in a certain function from the second interactive table is selected (e.g. error with index 3 corresponding to x error in x method), and the lines with the error are printed out or something similar. But I think this is more advanced and not so necessary as the first one. What do you think?

**Comment by galuhsahid** [comment]
I think we can tackle the first part first, and for the second one we can make that in a separate issue.

And yep the details should be in the wiki already, though I might need to style it up so it's easy to read and doesn't look too overwhelming. Will definitely ask for your input if needed!
